/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container': '#191f2f',
        'surface-container-high': '#232a3a',
        'surface-container-highest': '#2e3545',
        'surface-container-lowest': '#070e1d',
        'surface-container-low': '#141b2b',
        'surface': '#0c1322',
        'surface-dim': '#0c1322',
        'surface-bright': '#323949',
        'surface-variant': '#2e3545',
        'on-surface': '#dce2f7',
        'on-surface-variant': '#c3c6d7',
        'on-background': '#dce2f7',
        'background': '#0c1322',
        'primary': '#b4c5ff',
        'primary-container': '#2563eb',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary': '#002a78',
        'on-primary-container': '#eeefff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        'inverse-primary': '#0053db',
        'secondary': '#d4bbff',
        'secondary-container': '#7903fd',
        'secondary-fixed': '#ebdcff',
        'secondary-fixed-dim': '#d4bbff',
        'on-secondary': '#40008c',
        'on-secondary-container': '#e3d1ff',
        'on-secondary-fixed': '#260059',
        'on-secondary-fixed-variant': '#5c00c4',
        'tertiary': '#b2c5ff',
        'tertiary-container': '#3367d9',
        'tertiary-fixed': '#dae2ff',
        'tertiary-fixed-dim': '#b2c5ff',
        'on-tertiary': '#002b74',
        'on-tertiary-container': '#eef0ff',
        'on-tertiary-fixed': '#001848',
        'on-tertiary-fixed-variant': '#003fa3',
        'surface-tint': '#b4c5ff',
        'outline': '#8d90a0',
        'outline-variant': '#434655',
        'inverse-surface': '#dce2f7',
        'inverse-on-surface': '#293040',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        // Brand accent tokens used across the app (gradients, badges, glows)
        'gold': '#d4af37',
        'neon': '#00d2ff',
      },
      fontFamily: {
        headline: ['var(--font-space-grotesk)', 'Space Grotesk', 'sans-serif'],
        body: ['var(--font-inter)', 'Inter', 'sans-serif'],
        label: ['var(--font-inter)', 'Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
